
HERO_MOVE_SCALE = 4
HERO_IMAGE = "towerz/images/blue_rectangle.png"
ZOMBIE_IMAGE = "towerz/images/red_rectangle.png"
WALL_IMAGE = "towerz/images/wall_h.png"
HERO_Y = 100

MAX_X = 1200
MAX_Y = 800
HERO_SCALING = 0.01
ZOMBIE_SCALING = 0.2

HEALTHBAR_WIDTH = 25
HEALTHBAR_HEIGHT = 3
HEALTHBAR_OFFSET_Y = -10

HEALTH_NUMBER_OFFSET_X = -10
HEALTH_NUMBER_OFFSET_Y = -25

#Hero
HERO_HEALTHBAR_WIDTH = 250
HERO_HEALTHBAR_HEIGHT = 20
HERO_HEALTHBAR_OFFSET_Y = 0

HERO_HEALTH_NUMBER_OFFSET_X = 0
HERO_HEALTH_NUMBER_OFFSET_Y = 0

HERO_HEALTH_X = MAX_X/2
HERO_HEALTH_Y = 50

#Tower
TOWER_IMAGE = "towerz/images/gray_castle.png"
TOWER_SCALE = 0.8
TOWER_X = MAX_X / 2
TOWER_Y = MAX_Y / 2
TOWER_HEALTH = 500
TOWER_HEALTH_X = 1000
TOWER_HEALTH_Y = 50

#zombie
ZOMBIE_SPEED = 1
ZOMBIE_HIT = .1

#wall
WALL_SCALING = 1
WALL_LIFETIME = 7

#Resource
RESOURCE_IMAGE = "towerz/images/crystal2.png"
RESOURCE_SCALING = 0.1

RESOURCE_COUNTER_WIDTH = 250