
HERO_MOVE_SCALE = 2
HERO_IMAGE = "images/blue_rectangle.png"
ZOMBIE_IMAGE = "images/red_rectangle.png"
HERO_Y = 100

MAX_X = 1200
MAX_Y = 800
HERO_SCALING = 0.01
ZOMBIE_SCALING = 0.2

HEALTHBAR_WIDTH = 25
HEALTHBAR_HEIGHT = 3
HEALTHBAR_OFFSET_Y = -10

HEALTH_NUMBER_OFFSET_X = -10
HEALTH_NUMBER_OFFSET_Y = -25

HERO_HEALTHBAR_WIDTH = 400
HERO_HEALTHBAR_HEIGHT = 20
HERO_HEALTHBAR_OFFSET_Y = 0

HERO_HEALTH_NUMBER_OFFSET_X = 0
HERO_HEALTH_NUMBER_OFFSET_Y = 0

HERO_HEALTH_X = MAX_X/2
HERO_HEALTH_Y = 50

TOWER_IMAGE = "images/gray_castle.png"
TOWER_SCALE = 0.8
TOWER_X = MAX_X / 2
TOWER_Y = MAX_Y / 2
TOWER_HEALTH = 500